use std::env;
use std::fs;

#[derive(Debug, Clone)]
enum TokenKind {
    OpenMain,
        CloseMain,
            Print(String),
                Text(String),
                    End,
                    }

                    #[derive(Debug, Clone)]
                    struct Token {
                        kind: TokenKind,
                        }

                        /* =========================
                           SOURCE PREPROCESSOR
                           ========================= */
                           fn remove_print_statements(source: &str) -> String {
                               source
                                       .lines()
                                               .filter(|line| !line.trim_start().starts_with("/>print"))
                                                       .collect::<Vec<_>>()
                                                               .join("\n")
                                                               }

                                                               /* =========================
                                                                  LEXER
                                                                  ========================= */
                                                                  fn lexer(source: &str) -> Vec<Token> {
                                                                      let mut tokens = Vec::new();

                                                                          for line in source.lines() {
                                                                                  let l = line.trim();

                                                                                          if l == "</main>" {
                                                                                                      tokens.push(Token { kind: TokenKind::OpenMain });
                                                                                                              } else if l == "</main/>" {
                                                                                                                          tokens.push(Token { kind: TokenKind::CloseMain });
                                                                                                                                  } else if l.starts_with("/>print") {
                                                                                                                                              let text = l
                                                                                                                                                              .replace("/>print", "")
                                                                                                                                                                              .replace("</", "")
                                                                                                                                                                                              .trim()
                                                                                                                                                                                                              .trim_matches('"')
                                                                                                                                                                                                                              .to_string();

                                                                                                                                                                                                                                          tokens.push(Token {
                                                                                                                                                                                                                                                          kind: TokenKind::Print(text),
                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                              } else if l == "</end>" {
                                                                                                                                                                                                                                                                                          tokens.push(Token { kind: TokenKind::End });
                                                                                                                                                                                                                                                                                                  } else if !l.is_empty() {
                                                                                                                                                                                                                                                                                                              tokens.push(Token {
                                                                                                                                                                                                                                                                                                                              kind: TokenKind::Text(l.to_string()),
                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                          tokens
                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                          /* =========================
                                                                                                                                                                                                                                                                                                                                                             AST
                                                                                                                                                                                                                                                                                                                                                             ========================= */
                                                                                                                                                                                                                                                                                                                                                             #[derive(Debug)]
                                                                                                                                                                                                                                                                                                                                                             enum AstNode {
                                                                                                                                                                                                                                                                                                                                                                 Program(Vec<AstNode>),
                                                                                                                                                                                                                                                                                                                                                                     Print(String),
                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                     /* =========================
                                                                                                                                                                                                                                                                                                                                                                        PARSER
                                                                                                                                                                                                                                                                                                                                                                        ========================= */
                                                                                                                                                                                                                                                                                                                                                                        fn parser(tokens: Vec<Token>) -> AstNode {
                                                                                                                                                                                                                                                                                                                                                                            let mut nodes = Vec::new();

                                                                                                                                                                                                                                                                                                                                                                                for token in tokens {
                                                                                                                                                                                                                                                                                                                                                                                        if let TokenKind::Print(text) = token.kind {
                                                                                                                                                                                                                                                                                                                                                                                                    nodes.push(AstNode::Print(text));
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                    AstNode::Program(nodes)
                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                    /* =========================
                                                                                                                                                                                                                                                                                                                                                                                                                       CODE GENERATOR
                                                                                                                                                                                                                                                                                                                                                                                                                       ========================= */
                                                                                                                                                                                                                                                                                                                                                                                                                       fn codegen(ast: AstNode) {
                                                                                                                                                                                                                                                                                                                                                                                                                           if let AstNode::Program(nodes) = ast {
                                                                                                                                                                                                                                                                                                                                                                                                                                   for node in nodes {
                                                                                                                                                                                                                                                                                                                                                                                                                                               if let AstNode::Print(text) = node {
                                                                                                                                                                                                                                                                                                                                                                                                                                                               println!("{}", text);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /* =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          COMPILER ENTRY POINT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ========================= */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fn main() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              let args: Vec<String> = env::args().collect();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if args.len() < 2 {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          eprintln!("Usage: tahoe_compiler <file.tahoe>");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          let filename = &args[1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              let source = fs::read_to_string(filename)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .expect("Failed to read Tahoe source file");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          let cleaned = remove_print_statements(&source);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              let tokens = lexer(&cleaned);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  let ast = parser(tokens);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      codegen(ast);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }